service: ac-it

frameworkVersion: "3"
configValidationMode: error

plugins:
  - serverless-go-plugin

custom:
  go:
    supportedRuntimes: ["provided.al2023"]
    buildProvidedRuntimeAsBootstrap: true

provider: ${file(./infra/serverless.config.yml)}
functions: ${file(./infra/serverless.functions.yml)}
resources: ${file(./infra/serverless.cloudformation.yml)}